### ISSUE TITLE
RuntimeError: Camera __init__ sequence did not complete.( Raspberry Pi Camera module v2 )

### ISSUE THREAD

**Issue by dlatldhs** [2022-BBI-BBO/BBI-BBO-Backend#6]
RuntimeError

RuntimeError: Camera __init__ sequence did not complete.
Traceback (most recent call last)

    File "/usr/lib/python3/dist-packages/picamera2/picamera2.py", line 123, in __init__

    self._open_camera()

    File "/usr/lib/python3/dist-packages/picamera2/picamera2.py", line 310, in _open_camera

    raise RuntimeError("Failed to acquire camera")

    During handling of the above exception, another exception occurred:
    File "/usr/lib/python3/dist-packages/flask/app.py", line 2464, in __call__

    return self.wsgi_app(environ, start_response)

    File "/usr/lib/python3/dist-packages/flask/app.py", line 2450, in wsgi_app

    response = self.handle_exception(e)

    File "/usr/lib/python3/dist-packages/flask/app.py", line 1867, in handle_exception

    reraise(exc_type, exc_value, tb)

    File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise

    raise value

    File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app

    response = self.full_dispatch_request()

    File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request

    rv = self.handle_user_exception(e)

    File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception

    reraise(exc_type, exc_value, tb)

    File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise

    raise value

    File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request

    rv = self.dispatch_request()

    File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request

    return self.view_functions[rule.endpoint](**req.view_args)

    File "/home/king/flask-server/index.py", line 113, in test_pic

    p , pic_path= cam2()

    File "/home/king/flask-server/index.py", line 23, in cam2

    picam2 = Picamera2()

    File "/usr/lib/python3/dist-packages/picamera2/picamera2.py", line 130, in __init__

    raise RuntimeError("Camera __init__ sequence did not complete.")

    RuntimeError: Camera __init__ sequence did not complete.

It works the first time you use the camera, but it doesn't work the second time. When I saved the picture, I checked if the picture name was duplicated, but it was not.

**Comment by dlatldhs** [comment]
camera 모듈 사용할 때 이거 close를 해줘야하는데 이걸 못해서 처음엔 작동되다가 두번째에 작동을 안했던 거임
-> `camera.close`
